### ISSUE TITLE
Improvement tracking issue

### ISSUE THREAD

**Issue by ProgramCrafter** [knstntn-asuoki/qubedao-oracle#1]
- [x] Source of price does not match in function `get_actual_price_huobi`
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/313ba04687e06f15a057e155b890dd3865e97abe/qubedao-oracle-node/scripts/client.js#L41
- [x] Something strange in `notification_body` (also this function seems unused)
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/313ba04687e06f15a057e155b890dd3865e97abe/qubedao-oracle-node/scripts/client.js#L55
- [x] Probably unused function `update_price`
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/313ba04687e06f15a057e155b890dd3865e97abe/qubedao-oracle-node/scripts/client.js#L59
- [x] Is admin address used in smart contract?
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/main/qubedao-oracle-contract/func/core.func
- [x] Message should include time of fetching prices
- [x] Contract reads 2 prices per data source while JS application sends 1
- [x] Possible logic bug in smart contract: it's possible that price will not be added or will be added twice.
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/313ba04687e06f15a057e155b890dd3865e97abe/qubedao-oracle-contract/func/core.func#L26
  https://github.com/knstntn-asuoki/qubedao-oracle/blob/313ba04687e06f15a057e155b890dd3865e97abe/qubedao-oracle-contract/func/core.func#L29
- [x] Application sends new prices to smart contract only when it's requested. AFAIK this oracle should send prices regularly without any external requests.
  Also, if external requests are needed for updating price, there should be some throttling - otherwise messages could spend unlimited amount of oracle's TON leading to balance insufficient for working.
